"""add kultur to fields

Revision ID: fc5fcb151b52
Revises: 
Create Date: 2026-05-15 20:24:05.644051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5fcb151b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('einsatzorte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kultur_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_einsatzorte_kultur_id_kulturen', 'kulturen', ['kultur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('einsatzorte', schema=None) as batch_op:
        batch_op.drop_constraint('fk_einsatzorte_kultur_id_kulturen', type_='foreignkey')
        batch_op.drop_column('kultur_id')

    # ### end Alembic commands ###
